version: "3"

services:
  app:
    container_name: chatapi
    build: .
    restart: always
    ports:
      - "4000:4000"
    links:
      - mongoDB

  mongoDB:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
