apiVersion: v1
kind: Service
metadata:
  name: snap_share_service
spec:
  selector:
    app: snap_share
  ports:
    - port: 80
      targetPort: 4000
  type: LoadBalancer
---
apiversion: apps/v1beta1
kind: Deployment
metadata:
  name: snap_share_api_deployment
  tier: backend
  labels:
    app: snap_share
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snap_share
  template:
    metadata:
      labels:
        app: snap_share
    spec:
      containers:
        - name: snap_share
          image: brian/snap_share:1.0.0
          ports:
            - containerPort: 4000
          env:
            -name: MONGO_URL
             value: mongodb://mongo:27017/dev

